sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - "stable"
before_install:
  - npm i -g npm@^2.0.0
install:
  - npm install --no-shrinkwrap
before_script:
  - npm prune
script:
  - npm run lint
after_success:
  - npm run semantic-release
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
